apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-driven-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: {{ include "event-driven-app.name" . }}