apiVersion: v1
kind: ConfigMap
metadata:
  name: jmx-config
  namespace: default
data:
  config.yaml: |
    rules:
    - pattern: "kafka.server<type=(.+), name=(.+)><>Value"
      name: "kafka_server_$1_$2"
      type: GAUGE