apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: aakyuz1/consumer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: KAFKA_GROUP_ID
          value: "your-consumer-group"
        - name: KAFKA_TOPIC
          value: "your-topic"
        - name: KAFKA_RETRY_TOPIC
          value: "your-retry-topic"
        - name: KAFKA_DLQ_TOPIC
          value: "your-dlq-topic"
        - name: KAFKA_RETRY_BACKOFF_MS
          value: "5000"
        - name: KAFKA_MAX_RETRIES
          value: "3"
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"