apiVersion: v1
kind: ConfigMap
metadata:
  name: jmx-config
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
data:
  # ConfigMap içeriğini buraya ekleyin