apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    app: producer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080